#!/bin/bash

if [ -e "/home/tik/.config/autostart/org.opensuse.tik.desktop" ]; then
  # We are in the installer
  exit 0
fi

if [[ -f /etc/sysconfig/displaymanager ]]; then
  sed -i "s|DISPLAYMANAGER_AUTOLOGIN=.*|DISPLAYMANAGER_AUTOLOGIN=\"deck\"|g" /etc/sysconfig/displaymanager
fi

# set to default session
if [[ -f /var/lib/AccountsService/users/deck ]]; then
  sed -i "s|Session=.*|Session=default|g" /var/lib/AccountsService/users/deck
else
  echo "[User]" > /var/lib/AccountsService/users/deck
  echo "Session=default" >> /var/lib/AccountsService/users/deck
fi

# Set default session
if [[ -f /usr/share/wayland-sessions/gamescope-session-steam.desktop ]]; then
  ln -sf /usr/share/wayland-sessions/gamescope-session-steam.desktop /etc/alternatives/default-waylandsession.desktop
fi
